### ISSUE TITLE
Light Mode and other features

### ISSUE THREAD

**Issue by tedhong9** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#1]
Hi,
First of all, I want to thank you for this project! I loved it!
I would like to see a light mode option (my Windows theme is set to light).
Furthermore, I know this sounds like nitpicking, but could you update some fonts and formatting? If you ask for the weather, rainy days would be spaced weirdly (see attachment). Also, could you update the font so that it is Google's font everywhere? It would also be nice if you included speech bubbles for the user/Google Assistant's words.

By the way, I don't really want this to sound like nitpicking, but it was just something that bothered me.

Thank you so much!

![image](https://user-images.githubusercontent.com/62223616/78607820-aa4be100-7814-11ea-9226-61ef99b46348.png)

**Comment by Melvin-Abraham** [comment]
@tedhong9 Thanks for the compliment... 😊

**Light theme** is one of the milestones I am planning for. Also, I'm planning to change the themes based on system settings.

And talking about the **"Weather"** query, the last element would appear to be oddly spaced because it's one of the ways assistant tries to **scale** the contents within the window (for *original* scaling, you can uncheck *Enable Auto Scaling* in the settings and try again). Anyways, this will be dealt with soon.

The **fonts** and **speech bubbles** are not in current plan but might be figured out for later...

**Comment by tedhong9** [comment]
Thank you!
