### ISSUE TITLE
[Feature Request] Setting to default to Voice input

### ISSUE THREAD

**Issue by dopewind** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#17]
When we press Win+Shift+A, it could go directly to voice access mode. I mean we could have a option in settings for this as different people have different use cases

**Comment by Melvin-Abraham** [comment]
Please clarify your point with verbose description. Also, give a better, descriptive title for this issue...

**Comment by dopewind** [comment]
**@Melvin-Abraham **



For example, when we summon the Google Assistant on an Android ( either by swiping from corner on A10 and above or holding down home button on other versions ) the assistant opens and starts listening for voice input.

In your version, which works flawlessly BTW we need to press Win+Shift+A and the subsequently click on the voice button to make the assistant receive voice commands.

My suggestion was a setting (a toggle) which will make the assistant directly listen for voice commands when summoned or wait for the user to type down the command .

Please do reply if you didn't understand what I meant 😃

**Comment by Melvin-Abraham** [comment]
@dopewind Thank you for explaining that and fixing the title. This issue was already brought up in #3 and the commit fc3974c implemented it. This feature is now available as a part of `v1.0.0-rc.2` and can be accessed from **Settings** > **Conversation** > **Enable microphone on application startup**. If this helps, don't forget to close this issue. :)

**Comment by dopewind** [comment]
@Melvin-Abraham 

Thanks a lot for the fast suppor

Keep up the great work

Cheers✌
