### ISSUE TITLE
Unable to Access Personal Results

### ISSUE THREAD

**Issue by AyushEG** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#175]
This is great stuff, but here's an issue.

Me: "What's my name?"

GA: "First I'll need your permission to give Personal Results. You can make that change in Google Assistant Settings on your phone."

*gets a notification on my phone to allow personal results for assistant device. clicks allow, app crashes. in the end, PC still can't access personal results.*

**Comment by kbdharun** [comment]
Hello @AyushEG, 

Please note that this client is an **Unofficial client** and this Client uses _Google's_ **Assistant API**, So the API is meant for testing and developing purposes only, So the Client doesn't have the Full Functionality Of Google Assistant in Android Devices and Chromebooks. 

**Also, please don't use your Personal Email Address with this client I suggest you Create A Burner account for using this client** as Google might Ban or Block your account in the Future over using its API against its terms and Conditions.

But this issue you have Is not due to the client it is due to Your Preference in your Google Account.

To enable Personal Results follow this Google's Article on [How to Enable Personal Results in Google Assistant](https://support.google.com/assistant/answer/7684543?co=GENIE.Platform%3DAndroid&hl=en). 

Hope this Helps.

Regards, 
K.B.Dharun Krishna
`Windows Geek`

**Comment by Greg5463** [comment]
I can confirm that personal results used to work before. Then out of no where, it stopped working. Last time I can confirm that it used to work was last Thursday. 

I also get a notification from my phone to allow personal results, but the device name is blank. And if you leave it blank while enabling personal result, it crashes. However, if you give it a name an then enable personal result, it does not crash, but it does not save?

This is really weird and I really would like to have it fixed

**Comment by Melvin-Abraham** [comment]
This seems to be a legit problem. I tried getting it to work in many ways but failed. Also, there doesn't seem to be any useful workaround on the internet. If anyone has any ideas regarding how to get it working, please do share it here...

**Comment by aagha** [comment]
It's not clear to me how @kbdharun's suggestion helps:

https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/175#issuecomment-783802422

Enabling Personal Results doesn't seem to be possible unless a mechanism is provided from within the app.

**Comment by obed9057** [comment]
@kbdharun is trying to say that the developer cant do personal account results unless the developer codes an ai machine to ask for the email address and check the search history of the account and to determine which one is relevant depending on the results.

**Comment by obed9057** [comment]
i tried my best to legitimately explain what he actually said...

**Comment by aagha** [comment]
Thanks.

Re https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/175#issuecomment-824457623, I got the impression he was saying that there was a toggle that could be changed. My initial hope was this was a Google Account setting, but it seems to be specific to a device, so I guess for now we're out of luck.

**Comment by kbdharun** [comment]
> It's not clear to me how @kbdharun's suggestion helps:
> 
> https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/175#issuecomment-783802422
> 
> Enabling Personal Results doesn't seem to be possible unless a mechanism is provided from within the app.
> 

**You can enable personal results for your account if you have an android device by going to google assistant settings and going into personalization setting and enabling personal results** even though you enabled it in your account you won't notice a change because you won't get most functionality of an official google assistant. After all, we use this workaround using assistant API which is restrictive in the case of personal results. After all, the reason is this API is used by developers to create smart home devices with google assistant you can't send a message from a smart light bulb or router this is due to the restrictive nature of the API, but some personal results like calendar results are possible in this client.

Screenshots for reference to enable personal results in Android, even when enabled the client can't view your emails, etc. Like the official client does.

![Screenshot_2021-04-22-08-09-52-728_com.google.android.googlequicksearchbox.jpg](https://user-images.githubusercontent.com/26346867/115648536-39a23480-a343-11eb-9157-f4a96278c0d5.jpg)
![Screenshot_2021-04-22-08-09-59-091_com.google.android.googlequicksearchbox.jpg](https://user-images.githubusercontent.com/26346867/115648546-3eff7f00-a343-11eb-8974-fefb37d6aa4e.jpg)

Hope this helps,
Regards,
K.B.Dharun Krishna
`Tech Nerd`

**Comment by kbdharun** [comment]
>  @kbdharun is trying to say that the developer can do personal account results unless the developer codes an ai machine to ask for the email address and check the search history of the account and determine which one is relevant depending on the results.

Even though he codes a Smart workaround the result would be restrictive because this is a developmental api for smart devices so when you set it up in the assistant console you come across a setting where you select the smart device because this is the purpose of API so you can't check your email in TV and other smart devices because there isn't still support for these functions.

**Comment by obed9057** [comment]
There might be a solution like (eg) making a ai bot to ask for the email address and check the search history of the account and determine which one is relevant depending on the results. but it has to be secure it has to be like the one google made but when will this be available only time will tell in the meantime try installing the client and if you're still having this request try using Siri Bixby or Cortana while you wait.

**Comment by obed9057** [comment]
Obviously, if you already have the client you can try coding the solution by yourself and sharing the code with Melvin-Abraham.

**Comment by kbdharun** [comment]
> There might be a solution like (eg) making a ai bot to ask for the email address and check the search history of the account and determine which one is relevant depending on the results. but it has to be secure it has to be like the one google made but when will this be available? only time will tell in the meantime try installing the client and if you're still having this request try using Siri Bixby or Cortana while you wait.

Only Google can bring a true full on client any unofficial client can't access the amount of personal details required by you for the client to use

**Comment by kbdharun** [comment]
> > There might be a solution like (eg) making a ai bot to ask for the email address and check the search history of the account and determine which one is relevant depending on the results. but it has to be secure it has to be like the one google made but when will this be available? only time will tell in the meantime try installing the client and if you're still having this request try using Siri Bixby or Cortana while you wait.
> 
> Only Google can bring a true full on client any unofficial client can't access the amount of personal details required by you for the client to use


So, better wait for sometime, time will tell whether there will be a Official app for Google assistant for PC like the existence of Alexa app.

**Comment by morgenman** [comment]
See this: 
https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184

**Comment by AyushEG** [comment]
> See this:
> [#53 (comment)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184)

This didn't work for me

**Comment by morgenman** [comment]
There must be some other setting I turned on. I will have to do more testing

**Comment by adithv08** [comment]
I actually got a notification to enable personal results but the problem is that the app crashes when I toggle it on

**Comment by morgenman** [comment]
You have to name it first.
I had to do it twice.

**Comment by adithv08** [comment]
What do you mean?

**Comment by Greg5463** [comment]
I can confirm doing what morgenman said works. And here how I made it work

1. I made a new token because asking personal stuff would not send a notification on my phone anymore. It seems to do that if the token is very old.
2. Once I got the notification on my phone, I pressed "allow" on the notification option thing, which opened the google home app. (I assume you need the app for this to work)
3. I named the device hello, pressed enter on my phone keyboard. renamed it to hello2, then I pressed allow personal information.
4. I then pressed the return key, and tested it on my PC and it worked!

Hope this helps

**Comment by AyushEG** [comment]
> I can confirm doing what morgenman said works. And here how I made it work
> 
> 1. I made a new token because asking personal stuff would not send a notification on my phone anymore. It seems to do that if the token is very old.
> 2. Once I got the notification on my phone, I pressed "allow" on the notification option thing, which opened the google home app. (I assume you need the app for this to work)
> 3. I named the device hello, pressed enter on my phone keyboard. renamed it to hello2, then I pressed allow personal information.
> 4. I then pressed the return key, and tested it on my PC and it worked!
> 
> Hope this helps

Crazy, this did the trick. Thanks! A more permanent solution would probably be something to look into, though @Melvin-Abraham

**Comment by diskreet90** [comment]
> See this:
> [#53 (comment)](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/53#issuecomment-875133184)

This worked flawless for me. Thanks for sharing that.

**Comment by kuriandungu** [comment]
On Pixel6Pro with Android 13 the Allow notification comes after you ask assistant you name on pc. however tapping it crashes the app on phone immediately. Trying on an older device with Android 7 opens the dialog. you enter device name and enable personalized results however it doesnt save.

**Comment by dlhtox** [comment]
I have tried this and it does not pop up anything on my phone.  I went through these instructions fresh and for the first time. 

I say "What is my name?" and it says the usual "First I'll need your permission to give Personal Results. You can make that change in Google Assistant Settings on your phone."

Nothing pops up on my phone and as this is a new install with a fresh token as it was a new configuration.

My phone is set up with two google accounts.  One is a Google Workspace (I think that's what it is called), the other is a regular Gmail account.

I use the Workspace account for my emails and calendar and all that.  By default, I use the normal Gmail account on my Google Assistant as the Workspace account isn't compatible with some things.  Not sure if that is my problem or not.

I would simply set it up for my regular Gmail account, but like I said, I use the Workspace account for my email and calendar and pretty much everything.

**Comment by sumeshir26** [comment]
@dlhtox Hi! Try this: https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1465096952
