### ISSUE TITLE
Make assistant window draggable everywhere

### ISSUE THREAD

**Issue by LinqLover** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#178]
This client has a very modern and minimalist UI. I'm actually surprised that it's not possible to drag the window everywhere, at least on Windows. This would be more intuitive because it's less hard to find the right place to drag, especially since title bar and window background both have the same color.

**Comment by esau-morais** [comment]
> To make the whole window draggable, you can add `-webkit-app-region: drag` as body's style:

```css
body { 
  -webkit-app-region: drag
}
```

**Note:** I just don't know if that's actually a good idea, once the user drags the mouse, it can actually select anotherelements.

**Comment by LinqLover** [comment]
> Note: I just don't know if that's actually a good idea, once the user drags the mouse, it can actually select other elements.

Surely this should not affect existing selection features. Do you know some good reference implementations for entire-window dragging? I feel like this is a pretty common pattern but I cannot tell a certain example at the moment ...

**Comment by esau-morais** [comment]
> Surely this should not affect existing selection features.

I don't actually code with Electron, but I was testing here and got to see that if I apply the code above, it still not working and selecting other elements. It probably is happening because the element needs to have a `no-drag` property to all the elements and it'd just increase the code. Let's see the position from the maintainer

**Comment by Melvin-Abraham** [comment]
> I'm actually surprised that it's not possible to drag the window everywhere, at least on Windows.

@LinqLover The window is draggable. You could drag it anywhere you want. Is there something else you are trying to convey? 🤔

**Comment by esau-morais** [comment]
> it's not possible to drag the window everywhere

What he is trying to say is that there's just a way to drag the window, using the title bar.

**Comment by Melvin-Abraham** [comment]
> > it's not possible to drag the window everywhere
> 
> What he is trying to say is that there's just a way to drag the window, using the title bar. So, his suggestion is to allow the user to drag it from everywhere in the window.

@esau-morais Okay. I get it now 😅

@LinqLover Unfortunately, that would require `-webkit-app-region: drag` for the `body` of the window. This would hand-over the control to the OS due to which click and other events won't be recognized by app. Of course, this could be fixed by adding `-webkit-app-region: no-drag` to such elements but unfortunately that would be tedious and might result in hard to maintain code. The worst part would be in case we accidently miss to apply `-webkit-app-region: no-drag` to some elements, it would not be clickable and would result in negative user experience. Keeping all that points, I think this would be too much work for less gain...

**Comment by esau-morais** [comment]
I think this issue can be closed, due to the inactivity time

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
