### ISSUE TITLE
Not working on Linux Kde neon.

### ISSUE THREAD

**Issue by niksingh710** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#23]
![Screenshot_20201026_224305](https://user-images.githubusercontent.com/60490474/97204895-af867280-17dc-11eb-85f9-7b76a43b0d0a.png)

after Setting the credential location I am getting this if I ignore this then paste my code then clicking submit does nothing.

Using Linux Kde neon based on ubuntu20.04 installed it via snap

**Comment by Melvin-Abraham** [comment]
@niksingh710 The reason behind this error is that the assistant was triggered (via _text_ or _microphone_) before the token file was created during which the assistant's `ready` event wasn't called. _I'll probably have an error message clearly stating that issue._

> after Setting the credential location I am getting this if I ignore this then paste my code then clicking submit does nothing

You can request tokens only once per day as per my testing _(that should explain this issue)_. So, maybe you can try fetching the tokens another day.

If this doesn't work, let me know... :)

**Comment by niksingh710** [comment]
@Melvin-Abraham I get what u r saying, I tried today too and got the same issue.

**Comment by Melvin-Abraham** [comment]
@niksingh710 The issue is pretty much still the same, assistant is triggered somehow before token is created. In your case this seems to be at the beginning, which could mean that it is being triggered right after the assistant is launched via the hotkey.

Typically, in **Settings** > **Application** > **Configure Hotkey Behavior**, the default hotkey behavior is "Launch app / Toggle Microphone". Generally, it does not cause any issue but in your case I can suggest the following: You can either set the value of _Configure Hotkey Behavior_ setting to any other option than the default one and launch assistant again or try launching via "Launch Assistant" option in the tray context menu.

Let me know if the issue still persists...

**Comment by niksingh710** [comment]
@Melvin-Abraham Nothing from ur side it was all what i messed up. when i first launched assistant it was showing microphone is not accessible so without setting assistant token i executed this command `sudo snap connect g-assist:audio-record`

This was executing microphoen.
