### ISSUE TITLE
Replace Depreciated/Unsupported Dependencies

### ISSUE THREAD

**Issue by VelocityDesign** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#25]
**Describe the bug**
A few different packages are depreciated or unsupported for NPM. 

**To Reproduce**
1. Download & Unzip 
2. Open Command Prompt (Windows) / Terminal (Ubuntu & Chronos)
3. run "npm install"
**Expected behavior**
All packages successfully install.
**Screenshots**
N/a
**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider Preview Version 2004 (Build 19569.1000), Windows 10 Pro 20H2, Ubuntu 20.04-20.10

**Additional context**

**Comment by Melvin-Abraham** [comment]
Seems like the dependencies are up-to-date. So, I suppose you are talking about the **Electron dev-dependency** which is still in `v9.0.3` instead of the latest version. The reason behind this is due to the native-module `grpc` support. If you check out the changelog of latest grpc version (`v1.24.3`), you might notice that it adds support for Electron 7, 8, and 9 which means if I update the electron dependency to the latest version 10.x.x, it wouldn't compile.

If I misunderstood you, let me know...

**Comment by Melvin-Abraham** [comment]
_Closing as stale_
