### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by Michael199723** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1909]
 - Version [e.g. 1.0.0-rc.1]

**Additional context**

**Comment by Melvin-Abraham** [comment]
@Michael199723 The reason is partly due to constant microphone usage which turned out to be a bug (see https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/30#issuecomment-718846607). This issue has been fixed but is yet to be released (which will happen soon) and will fix high battery drainage issue. If you want to test it by running/building on your own device, see [How to build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/CONTRIBUTING.md#how-to-build).

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
