### ISSUE TITLE
App conflict on opening with some settings when no valid token

### ISSUE THREAD

**Issue by eoliveau** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#377]
**Describe the bug**
I configured the app with : 

Window float behavior > close on blur
Enable microphone on application startup > yes

1) If i have the token error and delete the token file to configure it again.

The next time the app start, it open my navigator window to get the new token, the app blur, and close and i can never enter the token, i had to manually change the config file to change the window float behavior for the app to stay open.

2) When the app open without the token, there is a start() problem caused by the "Enable microphone on application startup", if i put it back to off, everythings ok.

**Expected behavior**

Maybe reset back these 2 options to default when the app isn't authenticated anymore so it doesn't conflict

**Comment by Melvin-Abraham** [comment]
> The next time the app start, it open my navigator window to get the new token, the app blur, and close and i can never enter the token

This issue has already been fixed in the source code as per d5c4cef704 but it's still to be released.

> When the app open without the token, there is a start() problem caused by the "Enable microphone on application startup"

This issue has already been fixed in the source code as per dd67747c0 but it's still to be released.

---

Additionally, in the new version "Fallback Mode" will also be available allowing anyone to temporarily set the settings to defaults.
