### ISSUE TITLE
Unexpected Exception Occured 

### ISSUE THREAD

**Issue by mxcyborg** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#39]
Unexpected Exception Occured
An unexpected error occurred.
Error: Tried calling start() before the ready event!

I set up my google actions and added the key file path. then this appeared and i cant get rid of it
![Screenshot_1](https://user-images.githubusercontent.com/75050555/100294538-f9e74480-2f7e-11eb-8e76-085da2e90630.png)

**Comment by Melvin-Abraham** [comment]
Similar to issues: #23 and #21

**Comment by Melvin-Abraham** [comment]
Fixed in dd67747. Since, this fix will not be readily available until next release, you can either clone this project and build it yourself or if you do not want to build it yourself, you can _temporarily_ disable **Settings** > **Conversation** > **Enable microphone on application startup**, relaunch assistant and let the assistant save the tokens after which you can enable the setting again.
