### ISSUE TITLE
Scaling issue for Javascript error

### ISSUE THREAD

**Issue by WinnerWinds** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#412]
If the monitor resolution is more than 720p,  it will not render the application and runs into an error. this is commonly seen in issue #35 #80 If you set it to 720 p will full screen scaling the application _should_ bootup 

![image](https://user-images.githubusercontent.com/85327029/120754544-6f356280-c52a-11eb-9a71-5831490f8f65.png)
this is my before where it wouldnt work

![image](https://user-images.githubusercontent.com/85327029/120754593-7d837e80-c52a-11eb-9358-5e82ef41f170.png)
this is where it worked. i hope Melvin Abraham can somehow fix this

PS. after changing the resolution, changing it back will keep the application alive so its just a bootup issue.

**Comment by sumeshir26** [comment]
@WinnerWinds This issue has already been fixed in the build version and will be released very soon...
For more info [check the FAQs](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-do-i-get-typeerror-error-processing-argument-at-index-0)

**Comment by WinnerWinds** [comment]
Alright, im really bad at coding and commands so im scared i might mess up my computer by doing the build version. Thanks For the help. This thread will be closed. Thanks for everyone's time
