### ISSUE TITLE
Fonts not displaying

### ISSUE THREAD

**Issue by danhab99** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#486]
**Describe the bug**

Text on tray context menu and file browser displaying as error square characters.

**To Reproduce**
1. Install from SnapCraft
2. Setup until required to select "client secret" key file
3. See error

**Expected behavior**

UI is readable

**Screenshots**

![Screenshot from 2021-08-16 13-11-52](https://user-images.githubusercontent.com/13894263/129602780-21dd0c46-803c-43d9-adcb-a28d67a5430b.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 21.1.0 Pahvo
 - Version ?? (I can't get the version, I wrote this report right after installing)

**Additional context**

```
screenfetch -n
 dan@workstation
 OS: Manjaro 21.1.0 Pahvo
 Kernel: x86_64 Linux 5.10.53-1-MANJARO
 Uptime: 1h 14m
 Packages: 1706
 Shell: zsh 5.8
 Resolution: 5760x1080
 DE: GNOME
 WM: i3
 GTK Theme: Adwaita [GTK2/3]
 Icon Theme: Adwaita
 Font: Cantarell 11
 Disk: 338G / 984G (37%)
 CPU: Intel Core i9-10850K @ 20x 5.2GHz [60.0°C]
 GPU: NVIDIA GeForce RTX 2060
 RAM: 5621MiB / 32003Mi
```

**Comment by CryoRenegade** [comment]
Looks like a utf8 font mismatch

**Comment by Melvin-Abraham** [comment]
@danhab99 This issue seems to be exclusive to snaps, especially strictly confined snaps. This occurs because snaps tend to use fontconfig cache files instead of the fonts directly. A temporary solution for this is to remove the fontconfig cache which would force it to generate fresh cache files. You can refer [this GitHub issue comment](https://github.com/electron-userland/electron-builder/issues/5217#issuecomment-700707564) for more info...

**Comment by obed9057** [comment]
The version number is in the os name Lunix Manjaro 21.1.0 pahvo if you meant the assistant version go to the bottom of settings and under check fro updates it will say your version unless it needs an update

**Comment by obed9057** [comment]
i think it is a text error it may be that lunix is not allowed to show the system files because either the extension is encrypted or its not able to find the right font to use so it shows blanks it could sometimes happen in windows or mac too so its not just lunix that does this.

**Comment by im-coder-lg** [comment]
@obed9057 its not lunix, its Linux

**Comment by axzxc99** [comment]
This should still be open because the "fix" for it is not only temporary but also doesn't work for all systems.
screenfetch:
OS: Ubuntu 24.04 noble
 Kernel: x86_64 Linux 6.8.0-41-generic
 Packages: 2592
 Shell: bash 5.2.21
 CPU: Intel Core i5-7400T @ 4x 3GHz [53.0°C]
 GPU: Intel Corporation HD Graphics 630 (rev 04)
 RAM: 5148MiB / 11810MiB

**Comment by im-coder-lg** [comment]
@axzxc99 this is more of an issue with Snap than GAUDC, so it must be reported there.
Sorry for the late reply, I've been offline for a while.
