### ISSUE TITLE
Google assistant window not showing

### ISSUE THREAD

**Issue by Jujuf74** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#499]
**Describe the bug**
When launching no Debian 11, window is not showing at all (whatever through snap or direct appimage)
Shortcut (super+shift+A) doesn't do anything

(OS = Debian 11 + GNOME , PC= MSI N - Pentium N3700)

**Comment by im-coder-lg** [comment]
@Jujuf74 can you show a video on this bug?(Need some graphical example) PS: Since you use Debian, you must get a screen recorder. If you use Google Chrome or Chromium-based browsers, you can use Screenity, and upload the recording here.

**Comment by Melvin-Abraham** [comment]
@Jujuf74 Do you see any Google Assistant tray icon in your status bar?

**Comment by Jujuf74** [comment]
Hello, thanks for your reply

To answer your question :  nothing appears in the status bar or in application bar

I made a video (attached). I launch the application (installed with snap), nothing pops up, nothing int eh status bar or other, but as you can see in system monitor, the application (or part of it is running)

(I forgot to precise, but I used your latest RC = RC2)

https://user-images.githubusercontent.com/87944673/131357386-637a102c-553b-40c8-801e-0049a75cdfff.mp4

**Comment by Melvin-Abraham** [comment]
@Jujuf74 Does pressing <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>A</kbd> open up the window?

**Comment by Jujuf74** [comment]
No, nothing happens when pressing Windows+Shift+A. Itried to check if other system shorcut was already using this combination and found nothing

**Comment by Melvin-Abraham** [comment]
@Jujuf74 I guess that the tray icons are hidden by default and the fact that the key combination doesn't trigger a window start makes it obvious that the system is using a Wayland windowing system. Global shortcuts registered by apps are ignored in wayland, so, the user has to manually set a key combination for a particular command.

Anyway, for the time-being, I would suggest you head over to the `~/.config/Google Assistant/` directory and open `config.json`. There you should find the option `"hideOnFirstLaunch"`, which you must set to `false`. That way whenever you launch the assistant, the window will directly pop up. On top of that, you can set `"alwaysCloseToTray"` option to `false` as well so that launching the assistant again via the launcher or terminal after closing it won't show multiple instance error.

These are just workarounds for the latest version released (ie, `v1.0.0-rc.2`), so, you might not need those in the later releases. Most of the issues have kind of been addressed to some extent in the codebase itself. So you can try cloning the repo and building it to test out the app. Later on, wayland experience is planned to be enhanced.

**Comment by im-coder-lg** [comment]
Thought of saying to build the program but you solved it @Melvin-Abraham. But, you might need Node 14 and I know *how* to get it on. If you search `how to get node js 14 on debian` and open Tecmint's guide and follow *that*, then you have Node JS 14 LTS.

**Comment by im-coder-lg** [comment]
NPM bundled as usual

**Comment by Melvin-Abraham** [comment]
@Jujuf74 My bad. For `config.json` to show up, the assistant window should be launched initially for the first time at least. But you can create the config manually once to get it working. For that, head over to `~/.config/Google Assistant/`, create an empty file with the name `config.json`. Open the file and paste the following:

```json
{"hideOnFirstLaunch": false, "alwaysCloseToTray": false}
```

Now, save the file and start the assistant. Let us know if this doesn't work...

**Comment by Jujuf74** [comment]
Unfortunately not working (whatever snap or appimage). With the json.config, I can now clearly see the window opening but then it disappear (downwards for the record) and shorcut still not operating :-(

**Comment by im-coder-lg** [comment]
@Jujuf74 did you build the app via NPM first?

**Comment by Jujuf74** [comment]
Finally succeeded to rebuild the app and have it work with the json.config both on GNOME and XFCE. Thanks
(not sure it comes from this app but sometimes MPD (music player daemon) doesn't work when Google Assistant is on)
