### ISSUE TITLE
[💡 Feature Request]: A direct launch shortcut

### ISSUE THREAD

**Issue by gaussandhisgun** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#511]
### What's the Problem?

Currently, if I click on the Assistant shortcut in my tray, it either launches the app once or totally refuses to do anything because there are an instance running already.

### What's your solution or idea?

I would like that instead of this popup, while opening the shortcut and instance of app is already running, the Assistant window would open. I've seen some apps do that.
![изображение](https://user-images.githubusercontent.com/63512006/132402653-0b00c202-7909-4d88-b475-1f61e52ceaca.png)
That will also make things simpler for windows tablets.

### Alternatives Considered

I've tried using AutoHotKey, but its not nearly as native and also painfully slow.

### App Version

v1.0.0-rc.2

### OS Version

Windows 10 21H1

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one paricular feature request

**Comment by Melvin-Abraham** [comment]
@gaussandhisgun This issue has already been addressed and fixed in 72e3b2f1f. This is not released yet but will be released later on. Till then, if you want to try out the latest unreleased changes, you may want to refer to the [How to Build](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/blob/master/CONTRIBUTING.md#how-to-build) guide.

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
