### ISSUE TITLE
Приложение и различные клиенты 

### ISSUE THREAD

**Issue by VG584** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#518]

**Comment by Melvin-Abraham** [comment]
Please keep the issue content in English so that others can understand the issue and assist you. Also, please add a proper description. Create a new issue in [this link](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/new?assignees=Melvin-Abraham&labels=%F0%9F%90%9B+bug&template=bug_report.yml&title=%5B%F0%9F%90%9B+Bug%5D%3A+) on your desktop (not using phone). Once a proper issue is submitted, we will take a look :)

**Comment by Melvin-Abraham** [comment]
_Closing as invalid_
