### ISSUE TITLE
[💡 Feature Request]:  The Assistant Setup/Installer is out of date

### ISSUE THREAD

**Issue by clin366** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#519]
### What's the Problem?

Could you please update the installer to match the features? That would be really helpful for the new users, thank you!

### What's your solution or idea?

Upgrade the installer

### Alternatives Considered

update installer

### App Version

v1.0.0-rc.2

### OS Version

Mac

### Additional context

installer

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one paricular feature request

**Comment by im-coder-lg** [comment]
I understood the issue. You want the installer to be updated to synchronise with the latest features. That can happen in a new version only. Till then, if you compile the app from your computer, you can obtain an installer that has the latest features.

**Comment by clin366** [comment]
> I understood the issue. You want the installer to be updated to synchronise with the latest features. That can happen in a new version only. Till then, if you compile the app from your computer, you can obtain an installer that has the latest features.

Yes, I compiled the app using MacOS. I have two Macs Catalina and Big Sur, however, in both of them I installed the app successfully. But the google assistant voice query broke. I guess it is because of grpc and electron error. I can not solve the problem, I tried not to use @grpc/grpc-js and stick to an old version of electron, however, the voice query is still broken.

**Comment by im-coder-lg** [comment]
Looks like something broke. I think @Melvin-Abraham might know.On 11 Sep 2021 7:48 am, ***@***.***" ***@***.***> wrote:

I understood the issue. You want the installer to be updated to synchronise with the latest features. That can happen in a new version only. Till then, if you compile the app from your computer, you can obtain an installer that has the latest features.

Yes, I compiled the app using MacOS. I have two Macs Catalina and Big Sur, however, in both of them I installed the app successfully. But the google assistant voice query broke. I guess it is because of grpc and electron error. I can not solve the problem, I tried not to use @grpc/grpc-js and stick to an old version of electron, however, the voice query is still broken.

**Comment by Melvin-Abraham** [comment]
> But the google assistant voice query broke

@clin366 Can you send a screenshot/video for the same?

**Comment by im-coder-lg** [comment]
ping @clin366 can you share a recording of the issue?

**Comment by Melvin-Abraham** [comment]
A new version of the assistant has been released...

**Comment by Melvin-Abraham** [comment]
@im-coder-lg That seems to be an internal server error (external). Might remove that badge later...
