### ISSUE TITLE
[💡 Feature Request]: "ok google, hey google" detection

### ISSUE THREAD

**Issue by IceVDev** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#537]
### What's the Problem?

Why can't it be built in that it would trigger just like on phone?

### What's your solution or idea?

Just use the phone config files.

### Alternatives Considered

None.

### App Version

v1.0.0-rc.2

### OS Version

Win10 Envy  Processor	11th Gen Intel(R) Core(TM) i7-1165G7 

### Pre-submission Checklist

- [X] I have checked [the issue tracker](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues?q=is%3Aissue+label%3A%22%E2%9C%A8+enhancement%22+) and didn't find any duplicate issue
- [X] This issue only covers one paricular feature request

**Comment by im-coder-lg** [comment]
This has already been implemented but not released. You can build the app from source to get the feature. After building from source and opening the new version of the app, open Settings and toggle Ok Google/Hey Google, it will work.

**Comment by im-coder-lg** [comment]
Well, on deep reading, you can't use the phone config files since the Assistant SDK is open-source, the Assistant app is not. Google Assistant for Android is _closed-source_, meaning the Google devs only know the code. So, we needed to use another hotword program which is Bumblebee Hotword. Since Bumblebee is open-source, you can install, modify and publish your changes and et cetera. By default, Bumblebee has Ok Google and Hey Google so all it needed was some simple integration, so you can't use the phone config files since the config files reside inside the app, which is closed source as I said.

**Comment by yodaluca23** [comment]
I would download this 100% if it had this in the stable build.

**Comment by im-coder-lg** [comment]
Yo @yodaluca23 it's included in 1.0.0. Right now, GAUDC is going through a _major_ revamp(see #576) so there are not many commits in the `main` branch. There is almost 30+ commits in the [`next`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/tree/next) branch since that's the big revamp, like moving to React, using Vite(webserver maybe due to development) but till then, you can build the app for the latest fixes or get 1.0.0 and enable voice recog in the settings.

**Comment by yodaluca23** [comment]
When would that overhaul be coming out because I might just wait till then, then.

**Comment by Melvin-Abraham** [comment]
@yodaluca23

> When would that overhaul be coming out

That might actually take some time since almost all the code is being re-written from scratch. Till then you might get some minor updates over time.

> does it automatically update for that big overhaul or any future updates

Yes, since v1.0.0, support for auto-update has been baked in and is available based on the platform and package type that you installed on your machine. If you are using `deb` or `rpm` packages on Linux, you will have to manually download the installer and install it (as of v1.0.0), although, you will be notified about the update.

**Comment by Melvin-Abraham** [comment]
This feature has been made available in [`v1.0.0`](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/releases/tag/v1.0.0).

_Closing as resolved_
