### ISSUE TITLE
my location is far from my real

### ISSUE THREAD

**Issue by fabrixx** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#60]
If I type "take me to work" the destination path is correct but the departure is from "Daniela saviori, 24054 Calcio BG" why does this address appear as I live very far from there? The same address is associated with my location. 

Who is Daniela Savori? Why that address is associate with my Google Account from this Application?

Is my privacy safe using this application?

from my desktop my position is in the right place

**Comment by Dixit-deegit** [comment]
You can use command lik "ok Google set my location to (your location)"

**Comment by fabrixx** [comment]
Yes give my my correct location, but if i say "take me to work" or take me in every place the starting point is Daniela saviori, 24054 Calcio BG every time...curious.

In google maps all is ok, very strange.

**Comment by Melvin-Abraham** [comment]
@fabrixx The results are mostly up to Google, since this application uses Google Assistant SDK in its core. This issue would be looked into later sometime. Also, are you getting the same location from Google Assistant in your device?

> Is my privacy safe using this application?

This application just serves you the results from the SDK based on your query and all the results stays within the application itself. If you still want to clear things up, you can just view the source code of the application ;)

**Comment by Melvin-Abraham** [comment]
This issue will now be tracked in #257.
_Closing this issue_
