### ISSUE TITLE
UI not showing on screen

### ISSUE THREAD

**Issue by kaiichou** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#644]
app is clearly open in the taskbar, but the window itself is not showing on the screen.

**Comment by im-coder-lg** [comment]
Can you do these:
- Share a recording so that we could try knowing what is going wrong
- send a screenshot of GAUDC DevTools(to do this, right click the taskbar/top bar icon and click Open DevTools. If it fails, follow the step at the end
- Try going to fallback mode, to do this, right click the GAUDC tray icon and click fallback mode.
If none of those work, remove the `%appdata%/Google Assistant` if on Windows or `~/.config/Google\ Assistant` if on Linux or Ill have to add path for macos, two mins.

**Comment by kaiichou** [comment]
i just tried to reinstall it, and issue does not happen anymore. if it does happen again, i'll make sure to record everything and try your solution. thank you!
