### ISSUE TITLE
No response after I ask it a question

### ISSUE THREAD

**Issue by AnishDe12020** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#66]
I don't get any response from the application (no audio, visual or text response) after asking a question (refer to the attached screenshot)
![image](https://user-images.githubusercontent.com/63192115/104285585-def27480-54d9-11eb-9d52-798dfccc94b3.png)

I have completed the setup process and it doesn't give me any error for that. Also this used to work but after reinstalling it, it became buggy. I again tried reinstalling with no luck.

@Melvin-Abraham

**Comment by AnishDe12020** [comment]
I think I figured it out. Got a new client secret file and relogged in and now it works. I am closing the issue

**Comment by Melvin-Abraham** [comment]
@AnishDe12020 This generally happens when the Google Assistant API is not enabled

![Enable Google Assistant API](https://user-images.githubusercontent.com/26056183/104291312-64c5ee00-54e1-11eb-9882-6e761f4a0e8a.png)

You can follow steps 4 through 8 of [Guide: Configure Consent Screen](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#configure-consent-screen) if it happens again...
