### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by ItzMarSire** [Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client#79]
Seeing high memory usage in Task Manager, when its idle.

More than chrome, which is known to have high usage.

https://i.imgur.com/lmKBBD3.png

**Comment by Melvin-Abraham** [comment]
@ItzMarSire There have been some changes since `v1.0.0-rc.2` so the memory usage might be comparatively lower if not too low. One of the main issues which is currently fixed (but not released yet) was the constant use of microphone even when application is idle (see #30). This was in turn caused since old instances of microphone object were not reused/disposed and new instances were created instead causing memory leaks. Any more possible memory leaks will be tracked soon. For the time-being, you can clone this repo and build and test the memory usage difference. Also, if possible you can help with this issue by contributing to the repo... :)

**Comment by Melvin-Abraham** [comment]
_Closing as resolved_
